version: '3.8'

services:
  # Service BE
  longlearn-service:
    networks:
      - longlearnnetwork
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__Default=Server=154.26.128.219,1433;Database=TestDB;TrustServerCertificate=True;User Id=sa;Password=Long@1234
      - App__CorsOrigins=https://*.Docker.com,http://localhost:4200,http://154.26.128.219:4200
      - App__ClientUrl=http://154.26.128.219:4200
      - AuthServer__Authority=http://154.26.128.219:44342
    volumes:
      - /srv/www/Docker-DotNet-Angular/app-volumes/longlearn-service:/data
    ports:
      - 44342:80
    restart: always

  # Web FE
  longlearn-web:
    networks:
      - longlearnnetwork
    environment:
      - TZ=Asia/Ho_Chi_Minh
    ports:
      - 4200:80
    volumes:
      - /srv/www/Docker-DotNet-Angular/app-volumes/longlearn-web:/data
    restart: always
