# Build 
FROM node:16-alpine as build
WORKDIR /app
COPY /angular .
RUN yarn install
RUN yarn build:prod --output-path /app/dist

# # RUN
FROM nginx:1.20.1-alpine as final 
COPY --from=build /app/nginx.conf /etc/nginx/nginx.conf
COPY --from=build /app/dist /usr/share/nginx/html